#!/usr/bin/env python3
"""Build the Desktop V2 native core as a reproducible PyInstaller onedir component.

The generated spec is intentionally checked in through this script rather than
committing generated build output.  The build never uses PyInstaller's one-file
mode: the component manager installs an immutable directory tree and the
engine can start directly from it without extraction at runtime.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = ROOT / "backend"
ENTRYPOINT = BACKEND_ROOT / "native_engine.py"
CONTRACTS_ROOT = ROOT / "contracts" / "desktop-v2" / "schemas"
DEFAULT_OUTPUT = ROOT / "build" / "desktop-v2" / "native-engine"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--clean", action="store_true", help="Clear only the selected build output directory.")
    parser.add_argument("--dry-run", action="store_true", help="Write the spec and print the build plan without invoking PyInstaller.")
    parser.add_argument("--self-test", action="store_true", help="Run the built onedir executable's deterministic self-test.")
    return parser.parse_args()


def _spec_text(output_dir: Path) -> str:
    """Return a platform-neutral PyInstaller spec with absolute source paths."""

    def literal(path: Path) -> str:
        return repr(str(path.resolve()))

    return f'''# Generated by scripts/desktop-v2/build_native_engine.py.
# Do not change this to EXE(..., onefile=True): Desktop V2 installs an onedir tree.
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, collect_submodules

entrypoint = Path({literal(ENTRYPOINT)})
backend_root = Path({literal(BACKEND_ROOT)})
contracts_root = Path({literal(CONTRACTS_ROOT)})

def safe_data_files(package_name):
    try:
        return collect_data_files(package_name, include_py_files=True)
    except Exception:
        return []

def safe_dynamic_libs(package_name):
    try:
        return collect_dynamic_libs(package_name)
    except Exception:
        return []

def safe_submodules(package_name):
    try:
        return collect_submodules(package_name)
    except Exception:
        return []

datas = [(contracts_root, 'contracts/desktop-v2/schemas')]
datas += safe_data_files('qdrant_client')
datas += safe_data_files('pydantic')
datas += safe_data_files('pydantic_settings')

binaries = []
binaries += safe_dynamic_libs('asyncpg')
binaries += safe_dynamic_libs('qdrant_client')
binaries += safe_dynamic_libs('onnxruntime')

hiddenimports = [
    'native_engine',
    'config',
    'db.database',
    'db.models',
    'db.types',
    'aiosqlite',
    'aiosqlite.core',
    'aiosqlite.cursor',
    # asyncpg loads these compiled extensions dynamically.  PyInstaller cannot
    # infer them from SQLAlchemy's dialect import, so keep the two runtime
    # entry points explicit as well as collecting the full package below.
    'asyncpg.pgproto.pgproto',
    'asyncpg.protocol.protocol',
    'desktop_native.app',
    'desktop_native.health',
    'desktop_native.jobs',
    'desktop_native.logging_setup',
    'desktop_native.paths',
    'desktop_native.runtime',
    'desktop_native.sqlite_schema',
    'desktop_native.sqlite_storage',
    'desktop_native.tools',
    'desktop_native.vector_store',
    'api.routes.models',
    'api.routes.projects',
    'api.routes.videos',
    'services.ffmpeg',
    'services.native_semantic_compositor',
    'services.renderer',
    'services.tooling',
    'services.transcription',
    'rag.vector_store',
]
hiddenimports += safe_submodules('asyncpg')
hiddenimports += safe_submodules('qdrant_client')
hiddenimports += safe_submodules('sqlalchemy')

a = Analysis(
    [entrypoint],
    pathex=[backend_root, backend_root / 'app'],
    binaries=binaries,
    datas=datas,
    hiddenimports=sorted(set(hiddenimports)),
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pytest', 'tests', 'pkg_resources', 'setuptools'],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='aive-engine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='aive-engine',
)
'''


def write_spec(output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    spec_path = output_dir / "aive-engine.spec"
    spec_path.write_text(_spec_text(output_dir), encoding="utf-8", newline="\n")
    return spec_path


def _executable_path(output_dir: Path) -> Path:
    name = "aive-engine.exe" if sys.platform == "win32" else "aive-engine"
    return output_dir / "dist" / "aive-engine" / name


def run_build(output_dir: Path, spec_path: Path, clean: bool) -> Path:
    if importlib.util.find_spec("PyInstaller") is None:
        raise RuntimeError(
            "PyInstaller is not installed; install the pinned requirements from "
            "scripts/desktop-v2/requirements-native-build.txt"
        )
    if clean:
        dist_dir = output_dir / "dist"
        work_dir = output_dir / "work"
        for candidate in (dist_dir, work_dir):
            if candidate.exists():
                shutil.rmtree(candidate)
    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        str(output_dir / "dist"),
        "--workpath",
        str(output_dir / "work"),
        str(spec_path),
    ]
    subprocess.run(command, cwd=ROOT, check=True)
    executable = _executable_path(output_dir)
    if not executable.is_file():
        raise RuntimeError(f"PyInstaller completed without the expected onedir executable: {executable}")
    return executable


def run_self_test(executable: Path) -> dict[str, object]:
    try:
        completed = subprocess.run(
            [str(executable), "--self-test"],
            cwd=executable.parent,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError("frozen engine self-test exceeded the 30-second build deadline") from exc
    if completed.returncode != 0:
        raise RuntimeError(
            f"frozen engine self-test failed with exit {completed.returncode}: {completed.stderr.strip()}"
        )
    try:
        payload = json.loads(completed.stdout.strip())
    except json.JSONDecodeError as exc:
        raise RuntimeError("frozen engine self-test did not emit JSON") from exc
    if (
        payload.get("packaging") != "onedir"
        or payload.get("status") != "ok"
        or payload.get("frozen") is not True
        or payload.get("runtime") != "frozen"
    ):
        raise RuntimeError(f"unexpected frozen engine self-test payload: {payload}")
    return payload


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    spec_path = write_spec(output_dir)
    plan = {
        "entrypoint": str(ENTRYPOINT),
        "outputDir": str(output_dir),
        "spec": str(spec_path),
        "packaging": "onedir",
        "oneFile": False,
    }
    if args.dry_run:
        print(json.dumps(plan, indent=2))
        return 0
    executable = run_build(output_dir, spec_path, args.clean)
    plan["executable"] = str(executable)
    plan["selfTest"] = run_self_test(executable) if args.self_test else None
    print(json.dumps(plan, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        raise SystemExit(f"build_native_engine.py: error: {error}")
