#!/usr/bin/env python3
"""Build the Desktop V2 native core as a reproducible PyInstaller onedir component.

The generated spec is intentionally checked in through this script rather than
committing generated build output.  The build never uses PyInstaller's one-file
mode: the component manager installs an immutable directory tree and the
engine can start directly from it without extraction at runtime.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = ROOT / "backend"
ENTRYPOINT = BACKEND_ROOT / "native_engine.py"
CONTRACTS_ROOT = ROOT / "contracts" / "desktop-v2" / "schemas"
DEFAULT_AUTHORIZED_ROOT = Path("C:/Users/Dv/Desktop/ai-video-editor-standalone-release-work/rebuild")


def _authorized_root() -> Path:
    override = os.environ.get("AIVE_REBUILD_ROOT")
    if override is not None and not override.strip():
        raise ValueError("AIVE_REBUILD_ROOT must name a meaningful owned directory")
    selected = Path(override) if override is not None else DEFAULT_AUTHORIZED_ROOT
    if not selected.is_absolute():
        raise ValueError("AIVE_REBUILD_ROOT must be an absolute owned directory")
    resolved = selected.resolve()
    if resolved == Path(resolved.anchor) or not resolved.name.strip(". "):
        raise ValueError("Authorized rebuild root cannot be a filesystem/drive root")
    if not resolved.is_dir():
        raise ValueError(f"Authorized rebuild root must be an existing owned directory: {resolved}")
    for candidate in (selected.absolute(), *selected.absolute().parents):
        if candidate.exists() or candidate.is_symlink():
            info = candidate.lstat()
            if candidate.is_symlink() or getattr(info, "st_file_attributes", 0) & 0x400:
                raise ValueError(f"Reparse/symlink authorized root rejected: {candidate}")
    if not ROOT.is_relative_to(resolved):
        raise ValueError(
            f"Source checkout {ROOT} must be beneath authorized rebuild root {resolved}; "
            "main-owned CI must explicitly set AIVE_REBUILD_ROOT"
        )
    for candidate in (ROOT, *ROOT.parents):
        info = candidate.lstat()
        if candidate.is_symlink() or getattr(info, "st_file_attributes", 0) & 0x400:
            raise ValueError(f"Reparse/symlink source checkout rejected: {candidate}")
    return resolved


AUTHORIZED_ROOT = _authorized_root()
DEFAULT_OUTPUT = ROOT / "build" / "rebuild" / "engine"


def validate_output(path: Path) -> Path:
    resolved = path.resolve()
    if resolved == AUTHORIZED_ROOT or not resolved.is_relative_to(AUTHORIZED_ROOT):
        raise ValueError(f"Output must be below authorized rebuild root: {path}")
    # Refuse junctions/symlinks in existing path components, including owned outputs.
    for candidate in (path.absolute(), *path.absolute().parents):
        if candidate.exists():
            stat = candidate.lstat()
            if candidate.is_symlink() or getattr(stat, "st_file_attributes", 0) & 0x400:
                raise ValueError(f"Reparse/symlink output path rejected: {candidate}")
    return resolved


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--clean", action="store_true", help="Clear only the selected build output directory.")
    parser.add_argument("--dry-run", action="store_true", help="Write the spec and print the build plan without invoking PyInstaller.")
    return parser.parse_args()


def _spec_text(output_dir: Path) -> str:
    """Return a platform-neutral PyInstaller spec with absolute source paths."""

    def literal(path: Path) -> str:
        return repr(str(path.resolve()))

    return f'''# Generated by scripts/rebuild/build_engine.py.
# Do not change this to EXE(..., onefile=True): Desktop V2 installs an onedir tree.
from pathlib import Path
import sys
import importlib
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, collect_submodules, copy_metadata

entrypoint = Path({literal(ENTRYPOINT)})
backend_root = Path({literal(BACKEND_ROOT)})
contracts_root = Path({literal(CONTRACTS_ROOT)})
sys.path[:0] = [str(backend_root), str(backend_root / "app")]

def safe_data_files(package_name):
    try:
        return collect_data_files(package_name, include_py_files=True)
    except Exception:
        return []

def safe_dynamic_libs(package_name):
    try:
        return collect_dynamic_libs(package_name)
    except Exception:
        return []

def safe_submodules(package_name):
    try:
        return collect_submodules(package_name)
    except Exception:
        return []

def production_storage_module(module_name):
    # Reject complete development subtrees before collect_submodules recurses.
    # Exact path segments retain runtime names such as "testing" or "testifier".
    return not any(part in ('test', 'tests', 'conftest') for part in module_name.split('.'))

storage_data_excludes = [
    'test', 'tests', 'test/**', 'tests/**',
    '**/test', '**/tests', '**/test/**', '**/tests/**',
    'conftest.py', '**/conftest.py', 'conftest.pyc', '**/conftest.pyc',
]

# Python 3.11 pkg_resources -> jaraco.context needs this vendored backport.
# Initialize setuptools' installed vendor setup for validation; keep the public
# hidden import so PyInstaller's pre-safe-import hook supplies its vendor alias.
required_runtime_imports = []
if sys.version_info < (3, 12):
    try:
        importlib.import_module('setuptools')
        importlib.import_module('backports.tarfile')
    except ImportError as exc:
        raise RuntimeError('Required setuptools runtime import unavailable: backports.tarfile') from exc
    required_runtime_imports.append('backports.tarfile')

# Required native storage packages must never degrade into an empty collection.
required_datas = []
required_binaries = []
required_imports = []
for package_name in ('lancedb', 'pyarrow'):
    try:
        importlib.import_module(package_name)
        package_datas = collect_data_files(package_name, excludes=storage_data_excludes)
        package_binaries = collect_dynamic_libs(package_name)
        package_imports = collect_submodules(
            package_name, filter=production_storage_module, on_error='raise'
        )
        if not package_imports:
            raise RuntimeError('no submodules collected')
        required_datas += package_datas
        required_datas += copy_metadata(package_name, recursive=True)
        required_binaries += package_binaries
        required_imports += package_imports
    except Exception as exc:
        raise RuntimeError('Required native package collection failed: ' + package_name) from exc

datas = [(str(contracts_root), 'contracts/desktop-v2/schemas')] + required_datas
datas += safe_data_files('qdrant_client')
datas += safe_data_files('pydantic')
datas += safe_data_files('pydantic_settings')

binaries = list(required_binaries)
binaries += safe_dynamic_libs('asyncpg')
binaries += safe_dynamic_libs('qdrant_client')
binaries += safe_dynamic_libs('onnxruntime')

hiddenimports = [
    'native_engine',
    'config',
    'db.database',
    'db.models',
    'db.types',
    'aiosqlite',
    'aiosqlite.core',
    'aiosqlite.cursor',
    # asyncpg loads these compiled extensions dynamically.  PyInstaller cannot
    # infer them from SQLAlchemy's dialect import, so keep the two runtime
    # entry points explicit as well as collecting the full package below.
    'asyncpg.pgproto.pgproto',
    'asyncpg.protocol.protocol',
    'lancedb',
    'pyarrow',
    'desktop_native.index_journal',
    'desktop_native.agent_transactions',
    'desktop_native.app',
    'desktop_native.health',
    'desktop_native.jobs',
    'desktop_native.logging_setup',
    'desktop_native.paths',
    'desktop_native.runtime',
    'desktop_native.sqlite_schema',
    'desktop_native.sqlite_storage',
    'desktop_native.tools',
    'desktop_native.vector_store',
    'api.routes.models',
    'api.routes.projects',
    'api.routes.videos',
    'services.ffmpeg',
    'services.native_semantic_compositor',
    'services.renderer',
    'services.tooling',
    'services.transcription',
    'rag.vector_store',
]
hiddenimports += required_imports
hiddenimports += required_runtime_imports
for package_name in ('api', 'services', 'providers', 'agents', 'models', 'rag', 'desktop_native'):
    hiddenimports += collect_submodules(package_name, on_error='raise')
hiddenimports += safe_submodules('asyncpg')
hiddenimports += safe_submodules('qdrant_client')
hiddenimports += safe_submodules('sqlalchemy')

a = Analysis(
    [entrypoint],
    pathex=[backend_root, backend_root / 'app'],
    binaries=binaries,
    datas=datas,
    hiddenimports=sorted(set(hiddenimports)),
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pytest', 'tests'],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='aive-engine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='aive-engine',
)
'''


def write_spec(output_dir: Path) -> Path:
    validate_output(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    spec_path = output_dir / "aive-engine.spec"
    validate_output(spec_path)
    spec_path.write_text(_spec_text(output_dir), encoding="utf-8", newline="\n")
    return spec_path


def _executable_path(output_dir: Path) -> Path:
    name = "aive-engine.exe" if sys.platform == "win32" else "aive-engine"
    return output_dir / "dist" / "aive-engine" / name


def run_build(output_dir: Path, spec_path: Path, clean: bool) -> Path:
    if sys.version_info[:3] != (3, 11, 15):
        raise RuntimeError("Build requires main-prepared Python 3.11.15")
    for distribution, expected in (("pyinstaller", "6.11.1"), ("pyinstaller-hooks-contrib", "2026.8")):
        try:
            actual = importlib.metadata.version(distribution)
        except importlib.metadata.PackageNotFoundError as exc:
            raise RuntimeError(f"Required build distribution missing: {distribution}=={expected}") from exc
        if actual != expected:
            raise RuntimeError(f"Required {distribution}=={expected}; found {actual}")
    validate_output(output_dir)
    for owned in (output_dir / "dist", output_dir / "work", output_dir / "cache"):
        validate_output(owned)
        if owned.exists():
            for current, dirs, files in os.walk(owned, followlinks=False):
                for name in dirs + files:
                    validate_output(Path(current) / name)
    if clean:
        dist_dir = output_dir / "dist"
        work_dir = output_dir / "work"
        for candidate in (dist_dir, work_dir):
            if candidate.exists():
                validate_output(candidate)
                if candidate.resolve().parent != output_dir.resolve():
                    raise ValueError(f"Unsafe owned build subpath: {candidate}")
                shutil.rmtree(candidate)
    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        str(output_dir / "dist"),
        "--workpath",
        str(output_dir / "work"),
        str(spec_path),
    ]
    environment = os.environ.copy()
    environment["PYINSTALLER_CONFIG_DIR"] = str(output_dir / "cache")
    subprocess.run(command, cwd=ROOT, env=environment, check=True)
    executable = _executable_path(output_dir)
    if not executable.is_file():
        raise RuntimeError(f"PyInstaller completed without the expected onedir executable: {executable}")
    return executable


def main() -> int:
    args = parse_args()
    output_dir = validate_output(args.output_dir)
    spec_path = write_spec(output_dir)
    plan = {
        "entrypoint": str(ENTRYPOINT),
        "outputDir": str(output_dir),
        "spec": str(spec_path),
        "packaging": "onedir",
        "oneFile": False,
    }
    if args.dry_run:
        print(json.dumps(plan, indent=2))
        return 0
    executable = run_build(output_dir, spec_path, args.clean)
    plan["executable"] = str(executable)
    plan["selfTest"] = "not run; main-owned acceptance"
    print(json.dumps(plan, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        raise SystemExit(f"build_engine.py: error: {error}")
