"use strict";
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module');
const[repoArg,outArg,modulesArg,electronArg]=process.argv.slice(2),repo=path.resolve(repoArg),out=path.resolve(outArg),modules=path.resolve(modulesArg||path.join(repo,'desktop/node_modules'));
fs.mkdirSync(out,{recursive:false});const requireDesktop=Module.createRequire(path.join(modules,'../package.json')),esbuild=requireDesktop('esbuild'),{_electron}=requireDesktop('playwright');let app;const cases=[];
const component=path.join(repo,'desktop/src/components/UploadPanel.tsx').replaceAll('\\','/');
const forbidden=['listenToNativeImportProgress','listProjectAssets','getProjectReadiness','getProject','createProject','listVideos','uploadProjectPrimaryVideo','uploadVideo','startNativePrimaryImport','pickNativePrimaryVideoPath','cancelNativeImport','uploadProjectAsset','updateProjectAssetMetadata','deleteProjectAsset','startVideoProcessing'].map(name=>`export const ${name}=async()=>{window.calls.push('FORBIDDEN-${name}');throw Error('Unexpected unrelated API');};`).join('');
const stub=forbidden+`export const isNativeDesktop=async()=>false;export const friendlyErrorMessage=e=>String(e.message||e);export async function listMaterials(){window.calls.push('list');window.inFlight++;window.maxInFlight=Math.max(window.maxInFlight,window.inFlight);try{if(window.fixture.error)throw Error(window.fixture.error);const captured=structuredClone(window.fixture.materials);if(window.fixture.delay){return await new Promise(resolve=>window.pendingReads.push(()=>resolve(captured)));}return captured;}finally{window.inFlight--;}}export async function uploadMaterial(file){window.calls.push('upload');const item={id:'new-material',filename:file.name,chunk_count:0};window.fixture.materials.push(item);return item;}export async function deleteMaterial(id){window.calls.push('delete');if(window.fixture.deleteError)throw Error(window.fixture.deleteError);window.fixture.materials=window.fixture.materials.filter(m=>m.id!==id);} `;
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{UploadPanel}from${JSON.stringify(component)};let root;window.mountFixture=f=>{if(root)root.unmount();window.fixture=f;window.calls=[];window.pendingReads=[];window.inFlight=0;window.maxInFlight=0;root=createRoot(document.getElementById('root'));root.render(React.createElement(UploadPanel,{onUpload:()=>window.calls.push('FORBIDDEN-processing')}));};window.unmountFixture=()=>root.unmount();`;
async function main(){await esbuild.build({stdin:{contents:entry,resolveDir:repo,sourcefile:'material-feedback-test.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',nodePaths:[modules],outfile:path.join(out,'component.js'),plugins:[{name:'private-material-fixture',setup(b){b.onResolve({filter:/(^|\/)lib\/api$/},()=>({path:'private',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:stub,loader:'js'}));}}]});fs.writeFileSync(path.join(out,'index.html'),'<html><body><div id="root"></div><script src="./component.js"></script></body></html>');fs.writeFileSync(path.join(out,'main.cjs'),"const{app,BrowserWindow}=require('electron');app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1000,height:1000,webPreferences:{contextIsolation:true,nodeIntegration:false}});w.loadFile(require('path').join(__dirname,'index.html'));});app.on('window-all-closed',()=>app.quit());");const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('AIVE_')||k.endsWith('_API_KEY')||k==='ELECTRON_RUN_AS_NODE')delete env[k];app=await _electron.launch({executablePath:electronArg||path.join(modules,'electron/dist/electron.exe'),args:[path.join(out,'main.cjs'),'--user-data-dir='+path.join(out,'shell')],env});const page=await app.firstWindow();await page.waitForFunction(()=>typeof window.mountFixture==='function');const material={id:'existing',filename:'owned-course.pdf',chunk_count:0};async function mount(f){await page.evaluate(f=>window.mountFixture(f),f);await page.getByText('Course Materials (RAG Knowledge Base)',{exact:true}).waitFor();}async function test(name,fn){try{await fn();cases.push({name,status:'passed'});}catch(e){cases.push({name,status:'failed',error:String(e)});}console.log(cases.at(-1).status+' '+name);}async function uploaded(){await page.getByLabel('Add course material',{exact:true}).setInputFiles({name:'owned-new.pptx',mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',buffer:Buffer.from('Synthetic UI fixture only')});await page.getByText('owned-new.pptx',{exact:true}).waitFor();}
await test('queued-upload-updates-to-actual-indexed-chunks-without-reopen',async()=>{await mount({materials:[]});await page.waitForFunction(()=>window.calls.includes('list'));await uploaded();await page.getByText('(Awaiting embedding)',{exact:true}).waitFor();await page.evaluate(()=>window.fixture.materials[0].chunk_count=3);await page.getByText('(3 chunks)',{exact:true}).waitFor();await page.waitForTimeout(2200);assert.deepEqual(await page.evaluate(()=>window.calls.filter(c=>c==='upload')),['upload']);assert.equal(await page.evaluate(()=>window.maxInFlight),1);});
await test('late-initial-read-cannot-drop-successful-upload',async()=>{await mount({materials:[],delay:true});await page.waitForFunction(()=>window.pendingReads.length===1);await uploaded();await page.evaluate(()=>window.pendingReads.shift()());await page.waitForTimeout(100);assert.equal(await page.getByText('owned-new.pptx',{exact:true}).count(),1);await page.evaluate(()=>window.fixture.delay=false);});
await test('late-pre-delete-read-cannot-resurrect-removed-material',async()=>{await mount({materials:[material]});await page.getByRole('button',{name:'Remove owned-course.pdf',exact:true}).waitFor();await page.evaluate(()=>window.fixture.delay=true);await page.waitForFunction(()=>window.pendingReads.length===1);await page.getByRole('button',{name:'Remove owned-course.pdf',exact:true}).click();await page.getByText('No materials uploaded.',{exact:false}).waitFor();await page.evaluate(()=>window.pendingReads.shift()());await page.waitForTimeout(100);assert.equal(await page.getByText('owned-course.pdf',{exact:true}).count(),0);});
await test('read-failure-retains-data-and-refresh-only-reads',async()=>{await mount({materials:[material]});await page.getByText('owned-course.pdf',{exact:true}).waitFor();await page.evaluate(()=>window.fixture.error='Owned material read failure');await page.getByText(/Owned material read failure/).waitFor();assert.equal(await page.getByText('owned-course.pdf',{exact:true}).count(),1);await page.evaluate(()=>{window.fixture.error=null;window.fixture.materials[0].chunk_count=3;});await page.getByRole('button',{name:'Refresh materials',exact:true}).click();await page.getByText('(3 chunks)',{exact:true}).waitFor();assert.ok((await page.evaluate(()=>window.calls)).every(x=>x==='list'));});
await test('failed-delete-preserves-row-and-shows-feedback',async()=>{await mount({materials:[{...material,chunk_count:3}],deleteError:'Owned removal failure'});await page.getByRole('button',{name:'Remove owned-course.pdf',exact:true}).click();await page.getByText(/Owned removal failure/).waitFor();assert.equal(await page.getByText('owned-course.pdf',{exact:true}).count(),1);});
await test('unmount-disposes-poll-and-ignores-late-read',async()=>{await mount({materials:[material]});await page.getByText('owned-course.pdf',{exact:true}).waitFor();await page.evaluate(()=>window.fixture.delay=true);await page.waitForFunction(()=>window.pendingReads.length===1);const before=await page.evaluate(()=>window.calls.length);await page.evaluate(()=>{window.unmountFixture();window.pendingReads.shift()();});await page.waitForTimeout(2200);assert.equal(await page.evaluate(()=>window.calls.length),before);assert.equal(await page.locator('#root').innerHTML(),'');});
await test('bounded-poll-pauses-honestly-and-read-only-refresh-resumes',async()=>{await page.clock.install();await mount({materials:[material]});await page.getByText('(Awaiting embedding)',{exact:true}).waitFor();await page.clock.fastForward(121000);await page.getByText('(Indexing not yet confirmed)',{exact:true}).waitFor();const before=await page.evaluate(()=>window.calls.length);await page.clock.fastForward(10000);assert.equal(await page.evaluate(()=>window.calls.length),before);await page.evaluate(()=>window.fixture.materials[0].chunk_count=3);await page.getByRole('button',{name:'Refresh materials',exact:true}).click();await page.getByText('(3 chunks)',{exact:true}).waitFor();});
assert.ok(!(await page.evaluate(()=>window.calls)).includes('FORBIDDEN-processing'));}
main().catch(e=>{cases.push({name:'harness',status:'failed',error:String(e)});console.error(String(e));}).finally(async()=>{if(app)await app.close();const receipt={status:cases.length===7&&cases.every(c=>c.status==='passed')?'passed':'failed',scope:'Actual production UploadPanel with real React in owned Electron; controlled read/upload/delete fixture only, no backend/provider/profile writes. Stale responses, bounded polling, disposal and accessibility by named controls.',cases};fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exitCode=receipt.status==='passed'?0:1;});
