"use strict";
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module');
const [repoArg,outArg,modulesArg,electronArg]=process.argv.slice(2),repo=path.resolve(repoArg),out=path.resolve(outArg),modules=path.resolve(modulesArg||path.join(repo,'desktop/node_modules'));
const req=Module.createRequire(path.join(modules,'../package.json')),esbuild=req('esbuild'),{_electron}=req('playwright');
fs.mkdirSync(out,{recursive:false});let app;const cases=[];
const stub=`
export const friendlyErrorMessage=e=>String(e.message||e);
export async function getProjectSourceSyncPlan(project){window.calls.push({kind:'read',project});if(window.fixture.readError)throw Error(window.fixture.readError);const captured=structuredClone(window.fixture.plans[project]);if(window.fixture.delayRead===project)return new Promise(resolve=>window.pendingReads.push(()=>resolve(captured)));return captured;}
export async function updateProjectAssetSyncOffset(project,id,payload){window.calls.push({kind:'save',project,id,payload});if(window.fixture.saveError)throw Error(window.fixture.saveError);const row=window.fixture.plans[project].assets.find(r=>r.asset.id===id);row.current_offset_seconds=payload.sync_offset_seconds;row.asset.sync_offset_seconds=payload.sync_offset_seconds;const result=structuredClone(row.asset);if(window.fixture.delaySave)return new Promise(resolve=>window.pendingSaves.push(()=>resolve(result)));return result;}
export async function applyProjectSourceSyncMetadata(project,force){window.calls.push({kind:'metadata',project,force});if(force)throw Error('Manual overwrite forbidden');return structuredClone(window.fixture.plans[project]);}
`;
const source=path.join(repo,'desktop/src/components/SourceSyncPanel.tsx');
const entry=`import React from'react';import{createRoot}from'react-dom/client';import{SourceSyncPanel}from${JSON.stringify(source.replaceAll('\\','/'))};let root;window.mountFixture=f=>{if(root)root.unmount();window.fixture=f;window.calls=[];window.saved=[];window.pendingReads=[];window.pendingSaves=[];root=createRoot(document.getElementById('root'));window.switchProject('A');};window.switchProject=p=>root.render(React.createElement(SourceSyncPanel,{projectId:p,onSaved:assets=>{window.saved.push({project:p,ids:assets.map(a=>a.id)});}}));window.unmountFixture=()=>root.unmount();`;
const asset=(project,role,id,name)=>({id,project_id:project,role,original_filename:name,filename:name,sync_offset_seconds:0});
function fixture(extra={}){const plans={};for(const project of ['A','B']){const assets=[asset(project,'primary',project+'-primary',project+' primary.mp4'),asset(project,'camera',project+'-camera',project+' camera.mp4')];plans[project]={project_id:project,reference_asset_id:assets[0].id,sync_basis:'metadata',warnings:['Review manual offsets before export.'],assets:assets.map(a=>({asset:a,reference_asset_id:assets[0].id,recommended_offset_seconds:0,current_offset_seconds:0,manual_adjustment_seconds:0,confidence:.4,method:'default_zero_offset',reason:'No recording anchor',needs_user_review:true,waveform_sync_ready:false,metadata_anchor:null}))};}return{plans,...extra};}
async function main(){
 await esbuild.build({stdin:{contents:entry,resolveDir:repo,sourcefile:'source-sync-test.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',nodePaths:[modules],outfile:path.join(out,'component.js'),plugins:[{name:'source-sync-fixture',setup(b){b.onResolve({filter:/(^|\/)lib\/api$/},()=>({path:'private',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:stub,loader:'js'}));}}]});
 const postcss=req('postcss'),tailwind=req('tailwindcss');const {pathToFileURL}=require('node:url');const config=(await import(pathToFileURL(path.join(repo,'desktop/tailwind.config.js')).href)).default;const css=await postcss([tailwind({...config,content:[{raw:fs.readFileSync(source,'utf8'),extension:'tsx'}]})]).process(fs.readFileSync(path.join(repo,'desktop/src/index.css'),'utf8'),{from:undefined});fs.writeFileSync(path.join(out,'style.css'),css.css);
 fs.writeFileSync(path.join(out,'index.html'),'<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script src="./component.js"></script></body></html>');
 fs.writeFileSync(path.join(out,'main.cjs'),"const{app,BrowserWindow}=require('electron');app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1000,height:850,webPreferences:{contextIsolation:true,nodeIntegration:false}});w.loadFile(require('path').join(__dirname,'index.html'));});app.on('window-all-closed',()=>app.quit());");
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('AIVE_')||k.endsWith('_API_KEY')||k==='ELECTRON_RUN_AS_NODE')delete env[k];app=await _electron.launch({executablePath:electronArg||path.join(modules,'electron/dist/electron.exe'),args:[path.join(out,'main.cjs'),'--user-data-dir='+path.join(out,'shell')],env});const page=await app.firstWindow();await page.waitForFunction(()=>typeof window.mountFixture==='function');
 const camera=()=>page.getByLabel('Offset in seconds for A camera.mp4',{exact:true});const save=()=>page.getByRole('button',{name:'Save offset for A camera.mp4',exact:true});
 async function mount(f=fixture()){await page.evaluate(f=>window.mountFixture(f),f);await camera().waitFor();await page.waitForFunction(()=>!document.querySelector('section').getAttribute('aria-busy')||document.querySelector('section').getAttribute('aria-busy')==='false');}
 async function test(name,fn){try{await fn();cases.push({name,status:'passed'});}catch(e){cases.push({name,status:'failed',error:String(e)});}console.log(cases.at(-1).status+' '+name);}
 await test('zero positive negative offsets use preserved API and actual saved callback',async()=>{await mount();for(const value of ['0','2.5','-1.5']){await camera().fill(value);await save().click();await page.waitForFunction(n=>window.saved.length===n,(value==='0'?1:value==='2.5'?2:3));assert.equal(await camera().inputValue(),value);}const calls=await page.evaluate(()=>window.calls.filter(c=>c.kind==='save'));assert.deepEqual(calls.map(c=>c.payload.sync_offset_seconds),[0,2.5,-1.5]);assert.ok(calls.every(c=>c.project==='A'&&c.id==='A-camera'));});
 await test('blank and out of range are blocked with associated accessible error',async()=>{await mount();for(const value of ['','3600.1','-3600.1']){await camera().fill(value);await save().click();assert.equal(await camera().getAttribute('aria-invalid'),'true');assert.match(await page.getByRole('alert').innerText(),/finite offset/);}assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.kind==='save').length),0);});
 await test('metadata suggestions explicitly preserve manual offsets and use force false',async()=>{await mount();await camera().fill('2.5');await save().click();await page.waitForFunction(()=>window.saved.length===1);await page.getByRole('button',{name:'Apply metadata suggestions',exact:true}).click();await page.waitForFunction(()=>window.saved.length===2);assert.equal(await camera().inputValue(),'2.5');assert.deepEqual(await page.evaluate(()=>window.calls.filter(c=>c.kind==='metadata')),[{kind:'metadata',project:'A',force:false}]);});
 await test('save failure preserves draft and permits explicit retry',async()=>{await mount(fixture({saveError:'Owned fixture save failed'}));await camera().fill('-2');await save().click();await page.getByText('Owned fixture save failed',{exact:true}).waitFor();assert.equal(await camera().inputValue(),'-2');assert.equal(await page.evaluate(()=>window.saved.length),0);await page.evaluate(()=>window.fixture.saveError=null);await save().click();await page.waitForFunction(()=>window.saved.length===1);assert.equal(await camera().inputValue(),'-2');});
 await test('late old project read cannot replace the new project',async()=>{await page.evaluate(f=>window.mountFixture(f),fixture({delayRead:'A'}));await page.waitForFunction(()=>window.pendingReads.length===1);await page.evaluate(()=>window.switchProject('B'));await page.getByLabel('Offset in seconds for B camera.mp4',{exact:true}).waitFor();await page.evaluate(()=>window.pendingReads.shift()());await page.waitForTimeout(50);assert.equal(await camera().count(),0);assert.equal(await page.getByLabel('Offset in seconds for B camera.mp4',{exact:true}).inputValue(),'0');});
 await test('late save and unmounted completion do not invoke another project callback',async()=>{await mount(fixture({delaySave:true}));await camera().fill('3');await save().click();await page.waitForFunction(()=>window.pendingSaves.length===1);await page.evaluate(()=>window.switchProject('B'));await page.getByLabel('Offset in seconds for B camera.mp4',{exact:true}).waitFor();await page.evaluate(()=>window.pendingSaves.shift()());await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>window.saved.length),0);await page.getByLabel('Offset in seconds for B camera.mp4',{exact:true}).fill('1');await page.getByRole('button',{name:'Save offset for B camera.mp4',exact:true}).click();await page.waitForFunction(()=>window.pendingSaves.length===1);await page.evaluate(()=>window.unmountFixture());await page.evaluate(()=>window.pendingSaves.shift()());await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>window.saved.length),0);});
 await test('dirty drafts disable refresh/apply and unrelated row draft survives saving another row',async()=>{await mount();await page.getByLabel('Offset in seconds for A primary.mp4',{exact:true}).fill('1');await camera().fill('2');assert.equal(await page.getByRole('button',{name:'Refresh source synchronization',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Apply metadata suggestions',exact:true}).isDisabled(),true);await save().click();await page.waitForFunction(()=>window.saved.length===1);assert.equal(await page.getByLabel('Offset in seconds for A primary.mp4',{exact:true}).inputValue(),'1');assert.equal(await camera().inputValue(),'2');});
 await test('load failure offers explicit retry and long filename wraps at small width',async()=>{const f=fixture({readError:'Owned load failure'});await page.evaluate(f=>window.mountFixture(f),f);await page.getByRole('button',{name:'Retry source synchronization',exact:true}).waitFor();await page.evaluate(()=>{window.fixture.readError=null;window.fixture.plans.A.assets[1].asset.original_filename='A very long camera source filename '.repeat(7)+'.mp4';});await page.getByRole('button',{name:'Retry source synchronization',exact:true}).click();await page.locator('input[type=number]').nth(1).waitFor();await page.evaluate(()=>document.getElementById('root').style.width='320px');await page.waitForTimeout(40);const bounds=await page.evaluate(()=>{const r=document.getElementById('root');return{width:r.clientWidth,scroll:r.scrollWidth};});assert.ok(bounds.scroll<=bounds.width+1,JSON.stringify(bounds));});
}
main().catch(e=>{cases.push({name:'harness',status:'failed',error:String(e)});console.error(String(e));}).finally(async()=>{if(app)await app.close();const passed=cases.length===8&&cases.every(c=>c.status==='passed');fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify({status:passed?'passed':'failed',scope:'Actual production SourceSyncPanel/emitted CSS, preserved API calls with deterministic source metadata; no provider/data/native renderer changes or installed claim',cases},null,2));console.log(JSON.stringify({status:passed?'passed':'failed',cases:cases.length,failures:cases.filter(c=>c.status==='failed')}));process.exitCode=passed?0:1;});
