'use strict';
// Main-owned boundaries; real files/crypto, substituted Electron safeStorage/net and child.
const assert=require('node:assert/strict'), fs=require('node:fs/promises'), fss=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test');
const {createRequire}=require('node:module'),{randomBytes,createCipheriv,createDecipheriv}=require('node:crypto'),{EventEmitter}=require('node:events');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),out=path.resolve(process.argv[3]||path.join(root,'.test-output/provider-bridge'));fss.mkdirSync(out,{recursive:true});
const compiled=path.join(root,'desktop/dist-electron/desktop/electron');
function load(name,mocks={}){const file=path.join(compiled,name+'.js'),module={exports:{}},actual=createRequire(file);vm.runInNewContext(fss.readFileSync(file,'utf8'),{module,exports:module.exports,require:id=>Object.hasOwn(mocks,id)?mocks[id]:actual(id),__dirname:path.dirname(file),__filename:file,process,Buffer,URL,Headers,Request,Response,AbortController,AbortSignal,setTimeout,clearTimeout,queueMicrotask,console},{filename:file});return module.exports;}
const util=load('util');
async function profile(t){const p=await fs.mkdtemp(path.join(out,'node-'));t.after(()=>fs.rm(p,{recursive:true,force:true}));return p;}
const SECRET='EXPLICIT-TEST-SECRET-ABCD';
function storage(){const key=randomBytes(32);let available=true;const safeStorage={isEncryptionAvailable:()=>available,encryptString(s){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),b=Buffer.concat([c.update(s,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),b]);},decryptString(b){const c=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAuthTag(b.subarray(12,28));return Buffer.concat([c.update(b.subarray(28)),c.final()]).toString('utf8');}};return {safeStorage,setAvailable:v=>available=v};}
test('vault serializes set/remove/snapshot and publishes only metadata; encrypted bytes survive reopen',async t=>{const p=await profile(t),mock=storage(),{Credentials}=load('credentials',{electron:mock}),c=new Credentials(p);const a=c.set('openai',SECRET),b=c.set('mistral','OTHER-TEST-SECRET'),d=c.remove('mistral');const snap=c.snapshot();await Promise.all([a,b,d]);assert.equal(JSON.stringify(await snap),JSON.stringify({openai:SECRET}));const raw=await fs.readFile(path.join(p,'credentials.json'),'utf8');assert.ok(!raw.includes(SECRET));assert.equal(JSON.stringify(await c.metadata()),JSON.stringify([{provider:'openai',configured:true}]));assert.equal((await new Credentials(p).snapshot()).openai,SECRET);});
test('corrupt/unreadable/malformed/decryption vault fails closed and never overwrites corrupt original',async t=>{const p=await profile(t),mock=storage(),{Credentials}=load('credentials',{electron:mock}),c=new Credentials(p),file=path.join(p,'credentials.json');for(const raw of ['{','null','[]','{"foreign":"YQ=="}','{"openai":"bad!"}','{"openai":"YQ=="}']){await fs.writeFile(file,raw);await assert.rejects(c.snapshot(),/CREDENTIAL_READ_FAILED/);if(raw!=='{"openai":"YQ=="}'){await assert.rejects(c.set('openai',SECRET),/CREDENTIAL_WRITE_FAILED/);assert.equal(await fs.readFile(file,'utf8'),raw);}}await fs.rm(file);await fs.mkdir(file);await assert.rejects(c.snapshot(),/CREDENTIAL_READ_FAILED/);});
test('vault unavailable encryption and invalid providers/controls are sanitized; absent empty vault allowed',async t=>{const p=await profile(t),mock=storage(),{Credentials}=load('credentials',{electron:mock}),c=new Credentials(p);mock.setAvailable(false);assert.equal(JSON.stringify(await c.snapshot()),'{}');await assert.rejects(c.set('openai',SECRET),/CREDENTIAL_WRITE_FAILED/);assert.throws(()=>c.set('unknown',SECRET),/INVALID_PROVIDER/);for(const value of ['',SECRET+'\n','\u0080','x'.repeat(8193),null])assert.throws(()=>c.set('openai',value),/INVALID_CREDENTIAL/);mock.setAvailable(true);await c.set('openai',SECRET);mock.setAvailable(false);await assert.rejects(c.snapshot(),/CREDENTIAL_READ_FAILED/);});
function supervisor(fetch){const {Supervisor}=load('supervisor',{electron:{net:{fetch}}});const s=new Supervisor({},()=>{}),abort=new AbortController();s.child={pid:12345};s.endpoint={url:'http://127.0.0.1:12345',token:'fixture-session',signal:abort.signal};return {s,abort};}
test('supervisor sync uses private authenticated POST and exact names-only acknowledgement',async()=>{let called;const {s}=supervisor(async(url,opt)=>{called={url,opt};return new Response(JSON.stringify({status:'applied',configuredProviders:['mistral','openai']}));});await s.syncCredentials({openai:SECRET,mistral:'OTHER'});assert.equal(called.url,'http://127.0.0.1:12345/engine-control/credentials');assert.equal(called.opt.headers.Authorization,'Bearer fixture-session');assert.equal(called.opt.redirect,'error');assert.equal(called.opt.method,'POST');assert.equal(JSON.parse(called.opt.body).openai,SECRET);});
test('supervisor rejects invalid snapshots before network and sanitizes failed/incorrect acknowledgements',async()=>{let count=0;const {s}=supervisor(async()=>{count++;throw Error(SECRET);});for(const snap of [null,[],{unknown:SECRET},{openai:''},{openai:SECRET+'\n'}])await assert.rejects(s.syncCredentials(snap),/CREDENTIAL_SYNC_FAILED/);assert.equal(count,0);await assert.rejects(s.syncCredentials({openai:SECRET}),e=>e.message==='CREDENTIAL_SYNC_FAILED');for(const ack of [{status:'applied',configuredProviders:['openai','openai']},{status:'applied',configuredProviders:['unknown']},{status:'applied',configuredProviders:[]},{status:'wrong',configuredProviders:['openai']}]){const fixture=supervisor(async()=>new Response(JSON.stringify(ack)));await assert.rejects(fixture.s.syncCredentials({openai:SECRET}),/CREDENTIAL_SYNC_FAILED/);}});
test('stale child/endpoint or aborted session cannot accept a delayed credential acknowledgement',async()=>{for(const change of ['child','endpoint','abort']){let finish;const fixture=supervisor(()=>new Promise(r=>finish=r));const pending=fixture.s.syncCredentials({openai:SECRET});if(change==='child')fixture.s.child={pid:777};if(change==='endpoint')fixture.s.endpoint={...fixture.s.endpoint};if(change==='abort')fixture.abort.abort();finish(new Response(JSON.stringify({status:'applied',configuredProviders:['openai']})));await assert.rejects(pending,/CREDENTIAL_SYNC_FAILED/);}});
const ts=createRequire(path.join(root,'desktop/package.json'))('typescript'),apiFile=path.join(root,'desktop/src/lib/api.ts'),code=ts.transpileModule(fss.readFileSync(apiFile,'utf8'),{fileName:apiFile,compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText;
function frontend(native=true,fail=false){const calls=[],network=[],window={setTimeout,clearTimeout,location:{href:native?'aive://app/':'http://localhost:5173/'}};if(native)window.aiveDesktop={async setCredential(p,v){calls.push(['set',p,v]);if(fail)throw Error(SECRET);},async removeCredential(p){calls.push(['remove',p]);}};const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,window,URL,Headers,Request,Response,FormData,Blob,AbortController,DOMException,TextEncoder,Uint8Array,atob,btoa,fetch:async(url,opt)=>{network.push({url,opt});return new Response('{}');},require(){throw Error('Unexpected require');}});return {api:module.exports,calls,network};}
test('Electron settings saves encrypted bridge operations before preference PUT with secrets removed',async()=>{const f=frontend(),input={domain_terms:['lecture'],api_keys:{openai:{api_key:' '+SECRET+' '},mistral:{clear:true},deepseek:{api_key:' '},alibaba:{api_key:null}}};await f.api.updateAISettings(input);assert.deepEqual(f.calls,[['set','openai',SECRET],['remove','mistral'],['remove','deepseek'],['remove','alibaba']]);assert.equal(f.network[0].url,'aive://app/api/v1/settings/ai');assert.equal(f.network[0].opt.body,JSON.stringify({domain_terms:['lecture']}));assert.equal(input.api_keys.openai.api_key,' '+SECRET+' ');});
test('whole renderer credential map validates before first write; failures never PUT or echo secrets',async()=>{for(const invalid of [{unknown:{api_key:SECRET}},{mistral:{use_env:true}},{mistral:{env_var:'OPENAI_API_KEY'}},{mistral:{api_key:SECRET+'\n'}},{mistral:{api_key:3}},{mistral:{extra:true}}]){const f=frontend();await assert.rejects(f.api.updateAISettings({api_keys:{openai:{api_key:SECRET},...invalid}}),e=>e.code==='INVALID_CREDENTIAL');assert.equal(f.calls.length,0);assert.equal(f.network.length,0);}const f=frontend(true,true);await assert.rejects(f.api.updateAISettings({api_keys:{openai:{api_key:SECRET}}}),e=>e.code==='CREDENTIAL_SYNC_FAILED'&&!e.message.includes(SECRET));assert.equal(f.network.length,0);});
test('browser settings preserves existing backend key transport',async()=>{const f=frontend(false),input={api_keys:{openai:{api_key:SECRET}}};await f.api.updateAISettings(input);assert.equal(f.calls.length,0);assert.equal(f.network[0].url,'http://localhost:8000/api/v1/settings/ai');assert.equal(f.network[0].opt.body,JSON.stringify(input));});
