"use strict";
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module');
const [repoArg,outArg,modulesArg,electronArg,mediaArg]=process.argv.slice(2),repo=path.resolve(repoArg),out=path.resolve(outArg),modules=path.resolve(modulesArg),media=JSON.parse(fs.readFileSync(mediaArg,'utf8'));
const req=Module.createRequire(path.join(modules,'../package.json')),esbuild=req('esbuild'),{_electron}=req('playwright');fs.mkdirSync(out,{recursive:false});let app;const cases=[];
const secondary=path.join(repo,'desktop/src/components/SyncedSourceVideo.tsx').replaceAll('\\','/'),review=path.join(repo,'desktop/src/components/ReviewEditor.tsx').replaceAll('\\','/');
const stub=`export const isNativeBridgeEnabled=()=>Boolean(window.nativeBridge);export const friendlyErrorMessage=e=>String(e.message||e);export const getProjectAssetDownloadUrl=(p,id)=>'/api/v1/projects/'+p+'/assets/'+id+'/download';export function fetchEngineResource(p){return new Promise(resolve=>window.pendingBlobs.push({path:p,resolve}));}`;
const entry=`import React from'react';import{createRoot}from'react-dom/client';import{SyncedSourceVideo}from${JSON.stringify(secondary)};import{LayoutProgramPreview,resolvePreviewSource}from${JSON.stringify(review)};
let root;const ref=React.createRef();window.resolveSource=resolvePreviewSource;window.nativeBridge=false;window.pendingBlobs=[];window.mediaFile=${JSON.stringify(media.url)};
window.mountSource=props=>{if(root)root.unmount();root=createRoot(document.getElementById('root'));window.props=props;window.setSource({});};window.setSource=patch=>{Object.assign(window.props,patch);root.render(React.createElement(SyncedSourceVideo,window.props));};window.unmountSource=()=>root.unmount();
window.mountLayout=layout=>{if(root)root.unmount();root=createRoot(document.getElementById('root'));window.layout=layout;window.setLayout(layout);};window.setLayout=layout=>root.render(React.createElement(LayoutProgramPreview,{ref,src:window.mediaFile,settings:{layout,aspectRatio:'16:9',cameraShape:'rounded_rectangle',cameraCorner:'bottom_right',cameraSize:'medium',transitionDurationSeconds:.2},screenSource:{url:window.mediaFile,label:'Primary source',isPrimary:true,offsetSeconds:0},cameraSource:{url:window.mediaFile,label:'Selected real camera',isPrimary:false,offsetSeconds:2},isPlaying:false,generatedSlidePreview:{enabled:false,title:'',subtitle:'',sourceName:'',bullets:[]},annotations:[],educationalOverlays:[],endCards:[],currentTime:5,contentDuration:38}));window.master=()=>ref.current;`;
async function main(){
 const source=fs.readFileSync(review,'utf8');await esbuild.build({stdin:{contents:entry,resolveDir:repo,loader:'tsx'},bundle:true,jsx:'automatic',platform:'browser',format:'iife',nodePaths:[modules],outfile:path.join(out,'app.js'),plugins:[{name:'expose-production-and-private-resource',setup(b){b.onLoad({filter:/ReviewEditor\.tsx$/},()=>({contents:source+'\nexport {LayoutProgramPreview,resolvePreviewSource};',loader:'tsx',resolveDir:path.dirname(review)}));b.onResolve({filter:/(^|\/)lib\/api$/},()=>({path:'private',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:stub,loader:'js'}));}}]});
 const postcss=req('postcss'),tailwind=req('tailwindcss'),{pathToFileURL}=require('node:url'),cfg=(await import(pathToFileURL(path.join(repo,'desktop/tailwind.config.js')).href)).default;const css=await postcss([tailwind({...cfg,content:[{raw:source+'\n'+fs.readFileSync(secondary,'utf8'),extension:'tsx'}]})]).process(fs.readFileSync(path.join(repo,'desktop/src/index.css'),'utf8'),{from:undefined});fs.writeFileSync(path.join(out,'style.css'),css.css);
 fs.writeFileSync(path.join(out,'index.html'),'<html><head><link rel="stylesheet" href="style.css"></head><body><div id="root" style="width:640px;height:360px"></div><script src="app.js"></script></body></html>');fs.writeFileSync(path.join(out,'main.cjs'),"const{app,BrowserWindow}=require('electron');app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:900,height:600,webPreferences:{contextIsolation:true,nodeIntegration:false}});w.loadFile(require('path').join(__dirname,'index.html'));});app.on('window-all-closed',()=>app.quit());");
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('AIVE_')||k.endsWith('_API_KEY')||k==='ELECTRON_RUN_AS_NODE')delete env[k];app=await _electron.launch({executablePath:electronArg,args:[path.join(out,'main.cjs'),'--user-data-dir='+path.join(out,'shell')],env});const page=await app.firstWindow();await page.waitForFunction(()=>typeof window.mountSource==='function');
 async function test(name,fn){try{await fn();cases.push({name,status:'passed'});}catch(e){cases.push({name,status:'failed',error:String(e)});}console.log(cases.at(-1).status+' '+name);}
 async function mount(patch={}){await page.evaluate(p=>window.mountSource({...p,sourceUrl:window.mediaFile,label:'Owned camera',currentTime:5,offsetSeconds:2,isPlaying:false}),patch);await page.waitForFunction(()=>document.querySelector('video')?.readyState>=1);}
 async function at(time){await page.waitForFunction(time=>{const v=document.querySelector('video');return v&&!v.seeking&&Math.abs(v.currentTime-time)<.08;},time);}
 await test('selected source identity and native offset precedence preserve project boundary',async()=>{const result=await page.evaluate(()=>{const video={id:'V',project_id:'P',project_asset_id:'primary'},camera={id:'C',project_id:'P',kind:'camera_video',role:'camera',status:'ready',mime_type:'video/mp4',original_filename:'camera.mp4',sync_offset_seconds:2};const cue={sources:{camera:{asset_id:'C',sync_offset_seconds:0,enabled:true}}};const selected=window.resolveSource('camera',cue,[camera],video),legacy=window.resolveSource('camera',{sources:{camera:{asset_id:'C',sync_offset_seconds:-1}}},[{...camera,sync_offset_seconds:0}],video),wrong=window.resolveSource('camera',cue,[{...camera,project_id:'Q'}],video),structure=window.resolveSource('screen',{sources:{screen:{asset_id:'S'}}},[{...camera,id:'S',role:'slides',sync_role:'structure_reference',kind:'slide_deck'}],video);return{selected,legacy,wrong,structure};});assert.equal(result.selected.offsetSeconds,2);assert.equal(result.selected.url,'/api/v1/projects/P/assets/C/download');assert.equal(result.legacy.offsetSeconds,-1);assert.equal(result.wrong.url,null);assert.equal(result.structure.url,null);assert.equal(result.structure.structure,true);});
 await test('real metadata seeks zero positive negative offsets and clamps duration',async()=>{await mount();await at(3);for(const offset of [0,2,-2]){await page.evaluate(offset=>window.setSource({currentTime:5,offsetSeconds:offset,isPlaying:false}),offset);await at(5-offset);}await page.evaluate(()=>window.setSource({currentTime:500,offsetSeconds:0,isPlaying:false}));await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.seeking&&Math.abs(v.currentTime-v.duration)<.08;});await page.evaluate(()=>window.setSource({currentTime:0,offsetSeconds:2,isPlaying:false}));await at(0);});
 await test('secondary follows play pause and seek while always muted',async()=>{await mount();await at(3);await page.evaluate(()=>window.setSource({isPlaying:true}));await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.paused&&v.currentTime>3.02;});assert.equal(await page.locator('video').evaluate(v=>v.muted),true);await page.evaluate(()=>window.setSource({isPlaying:false,currentTime:9}));await at(7);assert.equal(await page.locator('video').evaluate(v=>v.paused),true);});
 await test('source replacement cleans old element and resets decoder errors',async()=>{await mount();await at(3);await page.evaluate(()=>{window.oldVideo=document.querySelector('video');window.setSource({sourceUrl:window.mediaFile+'?new-source',label:'Replacement camera'});});await page.getByLabel('Replacement camera',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('video')?.readyState>=1);assert.deepEqual(await page.evaluate(()=>({connected:window.oldVideo.isConnected,src:window.oldVideo.hasAttribute('src'),paused:window.oldVideo.paused})),{connected:false,src:false,paused:true});await page.evaluate(()=>window.setSource({sourceUrl:'file:///owned-fixture-does-not-exist.mp4'}));await page.getByText('This source is unavailable or cannot be decoded.',{exact:true}).waitFor();await page.evaluate(()=>window.setSource({sourceUrl:window.mediaFile,label:'Recovered source'}));await page.waitForFunction(()=>document.querySelector('video')?.readyState>=1);assert.equal(await page.getByText('This source is unavailable or cannot be decoded.',{exact:true}).count(),0);});
 await test('layout changes retain one master and show actual selected camera',async()=>{await page.evaluate(()=>window.mountLayout('picture_in_picture'));await page.getByLabel('Selected real camera',{exact:true}).waitFor();await page.evaluate(()=>window.originalMaster=window.master());for(const layout of ['side_by_side','full_camera_source','full_screen_source','picture_in_picture']){await page.evaluate(layout=>window.setLayout(layout),layout);await page.waitForFunction(layout=>{const v=window.master();return v===window.originalMaster&&v.isConnected&&document.querySelectorAll('video[aria-label="Primary playback"]').length===1;},layout);if(layout!=='full_screen_source')await page.getByLabel('Selected real camera',{exact:true}).waitFor();}assert.equal(await page.evaluate(()=>window.master()===window.originalMaster),true);});
 await test('late native resource response never installs an old source blob',async()=>{await page.evaluate(async()=>{window.fixtureBlob=await(await fetch(window.mediaFile)).blob();window.nativeBridge=true;window.pendingBlobs=[];window.mountSource({sourceUrl:'http://owned-fixture/A.mp4',label:'A source',currentTime:2,offsetSeconds:0,isPlaying:false});});await page.waitForFunction(()=>window.pendingBlobs.length===1);await page.evaluate(()=>window.setSource({sourceUrl:'http://owned-fixture/B.mp4',label:'B source'}));await page.waitForFunction(()=>window.pendingBlobs.length===2);await page.evaluate(()=>window.pendingBlobs[1].resolve(window.fixtureBlob));await page.waitForFunction(()=>document.querySelector('video')?.readyState>=1);const before=await page.locator('video').getAttribute('src');await page.evaluate(()=>window.pendingBlobs[0].resolve(window.fixtureBlob));await page.waitForTimeout(60);assert.equal(await page.locator('video').getAttribute('src'),before);assert.equal(await page.getByLabel('A source',{exact:true}).count(),0);await page.evaluate(()=>window.unmountSource());});
}
main().catch(e=>{cases.push({name:'harness',status:'failed',error:String(e)});console.error(String(e));}).finally(async()=>{if(app)await app.close();const pass=cases.length===6&&cases.every(c=>c.status==='passed');fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify({status:pass?'passed':'failed',scope:'Actual production source selection/SyncedSourceVideo/LayoutProgramPreview/emittedCSS using retained owned realcamera bytes and controlled private resource responses; no new media/provider/nativeoutput or installed claim',cases},null,2));console.log(JSON.stringify({status:pass?'passed':'failed',cases:cases.length,failures:cases.filter(c=>c.status==='failed')}));process.exitCode=pass?0:1;});
