'use strict';
// Execute the compiled main controller with Electron/component/credential substitutes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),{EventEmitter}=require('node:events'),{createRequire}=require('node:module');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),file=path.join(root,'desktop/dist-electron/desktop/electron/main.js');
const tick=()=>new Promise(r=>setImmediate(r));
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
async function fixture(){const log=[],app=new EventEmitter(),controls={required:false,keys:{},stop:async()=>{},prepare:async()=>{},cancel:()=>{},start:async()=>{}};let lastWindow;
 Object.assign(app,{isPackaged:true,getPath:()=>root,setPath(){},requestSingleInstanceLock:()=>true,whenReady:()=>Promise.resolve(),quit(){const evt={prevented:false,preventDefault(){this.prevented=true;}};app.emit('before-quit',evt);log.push(evt.prevented?'quit-blocked':'quit-confirmed');}});
 class BrowserWindow extends EventEmitter{constructor(){super();lastWindow=this;this.webContents={send(){},isDestroyed:()=>false,setWindowOpenHandler(){},on(){},session:{setPermissionRequestHandler(){},setPermissionCheckHandler(){},on(){}}};}isDestroyed(){return false;}loadURL(){return Promise.resolve();}show(){log.push('show');}isMinimized(){return false;}focus(){} }
 class Credentials{async metadata(){return [];}async snapshot(){log.push('snapshot');return {...controls.keys};}}
 class Components{constructor(paths,manifest,offline,publish){this.publish=publish;}async initialize(){log.push('initialize');}async allRequiredInstalled(){return controls.required;}async engine(){return {engine:{},root,ffmpegRoot:root,documentsRoot:root,libreofficeBinary:'',whisperRoot:root,whisperBinary:'',whisperModel:''};}async prepare(){log.push('prepare');await controls.prepare();}cancel(){log.push('cancel');controls.cancel();}async markReady(){log.push('markReady');}async localTranscriptionReady(){return false;}}
 class Supervisor{constructor(paths,changed){this.changed=changed;}async stop(){log.push('stop');await controls.stop();this.changed('stopped');}cancelStartup(){log.push('cancelStartup');}async start(){log.push('start');await controls.start();this.changed('ready');}async syncCredentials(){log.push('sync');}getEndpoint(){throw Error('unused');}}
 const mocks={electron:{app,BrowserWindow,protocol:{registerSchemesAsPrivileged(){},handle(){}},ipcMain:{handle(){}},dialog:{},shell:{},net:{}},'electron-updater':{autoUpdater:{}},'node:fs/promises':{appendFile:async()=>{}},'./util':{RELEASE:'2.1.0-rebuild.1',paths:async()=>({root,data:root,state:root,logs:root,components:root})},'./credentials':{Credentials},'./components':{Components},'./supervisor':{Supervisor},'./protocol':{handle(){},proxy(){},apiPath(){return true;}}};const actual=createRequire(file),module={exports:{}};
 const context=vm.createContext({module,exports:module.exports,require:id=>Object.hasOwn(mocks,id)?mocks[id]:actual(id),__dirname:path.dirname(file),__filename:file,process:{env:{LOCALAPPDATA:root},resourcesPath:root},Buffer,URL,Headers,Request,Response,AbortController,AbortSignal,setTimeout,clearTimeout,console});
 vm.runInContext(fs.readFileSync(file,'utf8')+'\nglobalThis.testHooks={prepare,restartEngine,mutateCredential,getState:()=>state,getQuitting:()=>quitting,setEngineState:value=>{state={...state,engineState:value};}};',context,{filename:file});await tick();await tick();log.length=0;
 return {app,controls,log,h:context.testHooks,quit(){app.quit();},lastWindow};
}
test('credential mutation and restart share queue; restart inner start does not deadlock',async()=>{const f=await fixture(),write=deferred();f.controls.required=true;f.h.setEngineState('ready');const credential=f.h.mutateCredential(async()=>{f.log.push('write');await write.promise;});await tick();const restart=f.h.restartEngine();await tick();assert.deepEqual(f.log,['write']);write.resolve();await credential;await restart;assert.deepEqual(f.log,['write','snapshot','sync','stop','snapshot','start','markReady']);assert.equal(f.h.getState().engineState,'ready');});
test('cancelling queued preparation stays immediate and never prepares or starts after stop',async()=>{const f=await fixture(),stop=deferred();f.controls.stop=()=>stop.promise;const pending=f.h.prepare();await tick();assert.equal(f.h.getState().canCancel,true);f.quit();assert.ok(f.log.includes('cancel'));assert.ok(f.log.includes('cancelStartup'));stop.resolve();await pending;await tick();await tick();assert.ok(!f.log.includes('prepare'));assert.ok(!f.log.includes('start'));assert.equal(f.log.at(-1),'quit-confirmed');});
test('quit drains current preparation and skips queued writes/restart/start before confirmed stop',async()=>{const f=await fixture(),preparation=deferred();f.controls.required=true;f.controls.prepare=()=>preparation.promise;f.controls.cancel=()=>preparation.reject(Error('cancelled'));const pending=f.h.prepare();await tick();assert.ok(f.log.includes('prepare'));const mutation=f.h.mutateCredential(async()=>f.log.push('write'));const rejected=assert.rejects(mutation,/DESKTOP_QUITTING/);f.quit();await pending;await rejected;await tick();await tick();assert.ok(!f.log.includes('write'));assert.ok(!f.log.includes('start'));assert.equal(f.log.at(-1),'quit-confirmed');});
test('failed stop blocks quit, restores retryable UI and allows later successful quit',async()=>{const f=await fixture();let calls=0;f.controls.stop=async()=>{if(++calls===1)throw Error('private failure');};f.quit();await tick();await tick();assert.equal(f.h.getQuitting(),false);assert.equal(f.h.getState().error.code,'ENGINE_STOP_FAILED');assert.ok(f.log.includes('show'));assert.ok(!f.log.includes('quit-confirmed'));f.quit();await tick();await tick();assert.equal(f.log.at(-1),'quit-confirmed');});
test('concurrent quit events stay prevented until owned shutdown resolves',async()=>{const f=await fixture(),stop=deferred();f.controls.stop=()=>stop.promise;f.quit();await tick();f.quit();assert.equal(f.log.filter(x=>x==='stop').length,1);assert.ok(!f.log.includes('quit-confirmed'));await assert.rejects(f.h.mutateCredential(async()=>{}),/DESKTOP_QUITTING/);stop.resolve();await tick();await tick();assert.equal(f.log.at(-1),'quit-confirmed');});
