'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module');
const [repoArg,outArg,mode='corrected',modulesArg,electronArg]=process.argv.slice(2),repo=path.resolve(repoArg),out=path.resolve(outArg);
const modules=path.resolve(modulesArg||path.join(repo,'desktop/node_modules')),req=Module.createRequire(path.join(modules,'../package.json')),esbuild=req('esbuild'),{_electron}=req('playwright');fs.mkdirSync(out,{recursive:false});let app;const cases=[];
const api=`export const isElectronDesktopRuntime=()=>Boolean(window.aiveDesktop);export const isTauriDesktopRuntime=async()=>false;export const setNativeBridgeEnabled=()=>{};export const setBaseUrl=()=>{};export const friendlyErrorMessage=e=>String(e.message||e);export async function getAISettings(){const value=structuredClone(window.fixture.settings);if(window.fixture.settingsDelay)return await new Promise(resolve=>window.pendingSettingsReads.push(()=>resolve(value)));return value;}export async function getLocalTranscriptionModels(){window.calls.push('catalog');return structuredClone(window.fixture.catalog);}export const getExportPresets=async()=>null;export const getVideo=async()=>null;export const getProject=async()=>null;export const testProviderConnection=async()=>({usable:false,message:'fixture'});export async function downloadLocalTranscriptionModel(id){window.calls.push('download:'+id);const m=window.fixture.catalog.models.find(m=>m.model_id===id);Object.assign(m,{status:'downloading',can_download:false,can_cancel:true,download_bytes_downloaded:12,download_progress_percent:50});return{status:'downloading'};}export async function cancelLocalTranscriptionModel(id){window.calls.push('cancel:'+id);Object.assign(window.fixture.catalog.models.find(m=>m.model_id===id),{status:'paused',can_cancel:false,can_resume:true});return{status:'paused'};}export const activateLocalTranscriptionModel=async()=>{window.calls.push('activate');return{};};export const removeLocalTranscriptionModel=async()=>{window.calls.push('remove');return{};};export async function updateAISettings(){window.calls.push('save');return structuredClone(window.fixture.settings);}`;
const appSource=path.join(repo,'desktop/src/App.tsx').replaceAll('\\','/');
function fixture(){return{settings:{preferred_processing_mode:'hybrid',fallback_enabled:true,asr_provider:'whisper',capabilities:{transcription:{mode:'hybrid',fallback_enabled:true,api_provider_id:'whisper'}},local_model_ids:{transcription:'small'},local_model_paths:{transcription:'/owned/small.bin'},provider_catalog:[]},catalog:{native:true,active_model_id:'small',runtime_configured:true,runtime_status:'ready',runtime_message:'Runtime ready',runtime_binary_path:'/owned/whisper-cli.exe',models:['small','medium','large-v3'].map((id,i)=>({model_id:id,label:'Whisper '+id,description:'Public fixture metadata',tier:'balanced',size:'Fixture size',speed:'CPU',quality:'Fixture',size_bytes:24,downloaded:i===0,active:i===0,bundled:i===0,file_path:i===0?'/owned/small.bin':null,status:i===0?'downloaded':'not_downloaded',can_download:i!==0,can_remove:false,can_cancel:false,can_resume:false,can_verify:false,download_progress_percent:0,download_bytes_downloaded:0,download_total_bytes:24}))}};}
async function main(){
 await esbuild.build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import{BrowserEditorApp}from${JSON.stringify(appSource)};const root=createRoot(document.getElementById('root'));window.mountFixture=(fixture,native)=>{window.fixture=fixture;window.calls=[];window.pendingSettingsReads=[];window.confirm=()=>true;window.aiveDesktop=native?{}:undefined;root.render(React.createElement(BrowserEditorApp,{key:native?'native':'legacy'}));};`,resolveDir:repo,loader:'tsx',sourcefile:'app-settings-navigation.tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',nodePaths:[modules],outfile:path.join(out,'app.js'),plugins:[{name:'controlled-boundaries',setup(b){
 b.onResolve({filter:/(^|\/)lib\/api$/},()=>({path:'api',namespace:'fixture'}));b.onResolve({filter:/(^|\/)provisioning$/},()=>({path:'provisioning',namespace:'fixture'}));b.onResolve({filter:/(components\/(UploadPanel|ProcessingView|ReviewEditor|ProjectDashboard|DesktopV2Shell|DesktopComponentManagementDialog)|electron\/ElectronSetup|^\.\/desktopV2$|@tauri-apps\/api\/core)/},a=>({path:a.path,namespace:'stub'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='api'?api:"export const provisioningClient=new Proxy({},{get:(_,k)=>()=>{window.calls.push('FORBIDDEN-'+String(k));throw Error('Unexpected legacy provisioning');}});",loader:'js'}));
 b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path.endsWith('desktopV2')?"export const resolveAppRoute=()=>'';":a.path.includes('@tauri')?"export const invoke=async()=>({});":['UploadPanel','ProcessingView','ReviewEditor','ProjectDashboard','DesktopComponentManagementDialog','DesktopV2Shell','DesktopV2ErrorBoundary','ElectronSetup'].map(n=>`export function ${n}(){return null}`).join(';'),loader:'js'}));
 } }]});
 fs.writeFileSync(path.join(out,'index.html'),'<html><body><div id="root"></div><script src="app.js"></script></body></html>');fs.writeFileSync(path.join(out,'main.cjs'),"const{app,BrowserWindow}=require('electron');app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1200,height:1000,webPreferences:{contextIsolation:true,nodeIntegration:false}});w.loadFile(require('path').join(__dirname,'index.html'));});app.on('window-all-closed',()=>app.quit());");
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('AIVE_')||k.endsWith('_API_KEY')||k==='ELECTRON_RUN_AS_NODE')delete env[k];app=await _electron.launch({executablePath:electronArg||path.join(modules,'electron/dist/electron.exe'),args:[path.join(out,'main.cjs'),'--user-data-dir='+path.join(out,'shell')],env});const page=await app.firstWindow();page.setDefaultTimeout(8000);await page.waitForFunction(()=>window.mountFixture);
 await page.evaluate(f=>window.mountFixture(f,true),fixture());await page.getByRole('button',{name:'Settings',exact:true}).click();if(mode!=='baseline'){assert.equal(await page.getByRole('button',{name:'Close settings',exact:true}).evaluate(e=>document.activeElement===e),true);assert.equal(await page.getByRole('dialog',{name:'Aivora settings',exact:true}).getAttribute('aria-modal'),'true');cases.push({name:'ordinary-settings-open-enters-named-modal',status:'passed'});}await page.getByRole('button',{name:'Local Models',exact:true}).click();
 if(mode==='baseline'){assert.equal(await page.getByRole('button',{name:'Manage local Whisper models',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Download Whisper medium',exact:true}).count(),0);assert.equal(await page.getByRole('dialog',{name:'Transcription',exact:true}).count(),0);cases.push({name:'actual-app-native-manager-unreachable-baseline',status:'proved-defect'});return;}
 const manage=page.getByRole('button',{name:'Manage local Whisper models',exact:true});await manage.waitFor();await manage.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Transcription',exact:true});await dialog.waitFor();assert.equal(await page.getByText('Workspace Settings',{exact:true}).count(),0);assert.equal(await dialog.getByRole('button',{name:'Download Whisper medium',exact:true}).isEnabled(),true);assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.startsWith('download:')).length),0);cases.push({name:'settings-local-models-keyboard-entry-opens-real-native-manager-without-acquisition',status:'passed'});
 await dialog.getByRole('button',{name:'Download Whisper medium',exact:true}).click();await dialog.getByRole('button',{name:'Cancel Whisper medium download or verification',exact:true}).waitFor();await dialog.getByRole('button',{name:'Cancel Whisper medium download or verification',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.calls.filter(c=>/^(download:|cancel:)/.test(c))),['download:medium','cancel:medium']);cases.push({name:'actual-app-path-reaches-existing-download-and-cancel-handlers',status:'passed'});
 await dialog.getByRole('button',{name:'Close transcription settings',exact:true}).click();await page.getByText('Workspace Settings',{exact:true}).waitFor();await manage.waitFor();await page.waitForFunction(()=>document.activeElement?.textContent?.trim()==='Manage local Whisper models');await manage.waitFor();assert.equal(await page.getByRole('dialog',{name:'Transcription',exact:true}).count(),0);await page.getByRole('button',{name:'Close settings',exact:true}).click();cases.push({name:'close-native-manager-restores-local-models-workspace-with-one-visible-panel',status:'passed'});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await manage.waitFor();await manage.click();await dialog.getByRole('button',{name:'Select Whisper small',exact:true}).waitFor();await page.evaluate(()=>window.fixture.settingsDelay=true);await dialog.getByRole('button',{name:'Close transcription settings',exact:true}).click();await page.waitForFunction(()=>window.pendingSettingsReads.length>0);await page.getByRole('button',{name:'Close settings',exact:true}).click();await page.evaluate(()=>{window.fixture.settingsDelay=false;while(window.pendingSettingsReads.length)window.pendingSettingsReads.shift()();});await page.getByRole('button',{name:'Settings',exact:true}).click();await manage.waitFor();assert.equal(await page.getByRole('button',{name:'Close settings',exact:true}).evaluate(e=>document.activeElement===e),true);cases.push({name:'abandoned-return-load-cannot-steal-focus-from-new-modal-entry',status:'passed'});
 await page.evaluate(f=>window.mountFixture(f,false),fixture());await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Local Models',exact:true}).click();await page.getByRole('button',{name:'Download',exact:true}).first().waitFor();assert.equal(await page.getByRole('button',{name:'Manage local Whisper models',exact:true}).count(),0);cases.push({name:'legacy-browser-keeps-original-local-model-controls',status:'passed'});
}
main().catch(e=>{cases.push({name:'navigation',status:'failed',error:String(e)});console.error(String(e));}).finally(async()=>{if(app)await app.close();const passed=mode==='baseline'?cases.length===1&&cases[0].status==='proved-defect':cases.length===6&&cases.every(c=>c.status==='passed');const receipt={status:passed?'passed':'failed',scope:'Production BrowserEditorApp/MainSettingsPanel/TranscriptionSettingsPanel navigation and real React handlers in existing hidden Electron; controlled API fixture/other app surfaces stubbed. No actual downloads/provider/installed-state claim.',cases};fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exitCode=passed?0:1;});
